apiVersion: apps/v1
kind: Deployment

metadata:
  name: devops-lab-site

spec:
  replicas: 2

  selector:
    matchLabels:
      app: devops-lab-site

  template:
    metadata:
      labels:
        app: devops-lab-site

    spec:
      containers:
        - name: devops-lab-site
          image: cloudlabhost/devops-lab-site:v1
          ports:
            - containerPort: 80